// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func Init() *App {
	config := NewConfig()
	dataBase := NewDB(config)
	service := NewService(dataBase)
	app := NewApp(service)
	return app
}
